# This is a basic workflow to help you get started with Actions

name: '手動トリガー'

on:
  workflow_dispatch
         
jobs:
  manual:
    name: 'Manual workflow'
    runs-on: ubuntu-latest

    steps:
    - name: Show events
      run: echo "${EVENT_ITEM}"
      env:
        EVENT_ITEM: ${{ toJson(github.event) }}

    - name: Show github
      run: echo "${CTX}"
      env:
        CTX: ${{ toJson(github) }} 

    - name: "Create artifact (${{ github.run_id }})"
      run: echo "${RUN_ID}" >> run-id.txt
      env:
        RUN_ID: ${{ github.run_id }}

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: item
        key: run-id.txt

    - name: Show artifact by curl
      run: |
        curl -i -H "Authorization: token ${TOKEN}" \
          "https://api.github.com/repos/mike-neck/actions-issue-comments/actions/runs/${RUN_ID}/artifacts"
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RUN_ID: ${{ github.run_id }}
