name: fork-join

on:
  workflow_dispatch: {}

jobs:
  pre:
    runs-on: ubuntu-20.04
    name: pre
    steps:
      - name: show your name
        run: echo "pre"
    
  fork:
    needs: [pre]
    runs-on: ubuntu-20.04
    name: "fork ${{ matrix.value }}"
    strategy:
      matrix:
        value: [foo, bar, baz]
    steps:
      - name: show value
        run: echo "${{ matrix.value }}"
      - name: fail on bar
        run: |
          if [[ "${VALUE}" == "foo" || "${VALUE}" == "baz" ]] ; then
            echo "Greate ${VALUE}"
            exit 0
          else
            echo "POOR ${VALUE}"
            exit 1
          fi
        env:
          VALUE: "${{ matrix.value }}"

  join:
    name: join
    runs-on: ubuntu-20.04
    needs: [fork]
    steps:
      - name: show your name
        run: echo "post"
