name: Issue created

on:
  issues:
    types: [opened]

jobs:
  show-event:
    name: Show event
    runs-on: ubuntu-latest

    steps:
      -
        name: Show event
        env:
          EVENT: ${{ toJson(github.event) }}
        run: echo "${EVENT}"

      -
         name: Export issue event
         env:
          EVENT: ${{ toJson(github.event) }}
         run: echo "${EVENT}" > ./event.json

      # 何が出るかな？
      -
         name: Store event
         uses: actions/upload-artifact@v2
         with:
           name: issue-event.json
           path: ./event.json
