name: pull request

on:
  pull_request:
    types: [opened, created, review_requested, synchronize, ready_for_review, edited, closed]

jobs:
  comment:
    name: Pull Request Opened/Created/Edited
    runs-on: ubuntu-latest

    steps:
      -
        name: Show github
        run: |
          echo "${OBJ}"
        env:
          OBJ: ${{ toJson(github) }}
