name: on push

on:
  push:
    branches:
      - master

jobs:
  merge:
    name: Pushed to master
    runs-on: ubuntu-latest

    steps:
      -
        name: Show github
        run: echo "${OBJ}"
        env:
          OBJ: ${{ toJson(github) }}
      -
         name: show jq path
         run: which jq
