name: on push

on:
  push:
    branches:
      - master

jobs:
  merge:
    name: Pushed to master
    runs-on: ubuntu-latest

    steps:
      -
        name: Show github
        run: echo "${OBJ}"
        env:
          OBJ: ${{ toJson(github) }}
      -
         name: show jq path
         run: which jq
      -
         name: show dict directory
         run: |
           ls /usr/share/dict/
           if [[ -f "/usr/share/dict/words" ]]; then
             wc -l "/usr/share/dict/words"
           fi

      -
         name: set item price
         run: |
           echo 'ITEM_PRICE=300' >> $GITHUB_ENV
           echo 'ITEM_CAKE=strawberry' >> $GITHUB_ENV

      - name: Show env
        run: env | grep "$(echo 'item' | tr a-z A-Z)"
        env:
          ITEM_NAME: foo
          ITEM_TITLE: bar
          CODE_NAME: baz
