name: on push

on:
  push:
    branches:
      - master

jobs:
  string-compare:
    name: String Compare
    strategy:
      matrix:
        key:
          - foo
          - bar
    runs-on: ubuntu-latest
    steps:
      - name: compare with foo
        run: echo "${{ matrix.key }}"
        if: matrix.key == 'foo'

      - name: write text
        run: echo 'foo' > text.txt

      - name: read text
        run: cat text.txt

  merge:
    name: Pushed to master
    runs-on: ubuntu-latest

    steps:
      -
        name: Show github
        run: echo "${OBJ}"
        env:
          OBJ: ${{ toJson(github) }}

      - name: show current directory
        run: pwd

      -
         name: show jq path
         run: which jq
      -
         name: show dict directory
         run: |
           ls /usr/share/dict/
           if [[ -f "/usr/share/dict/words" ]]; then
             wc -l "/usr/share/dict/words"
           fi

      -
         name: set item price
         run: |
           echo 'ITEM_PRICE=300' >> $GITHUB_ENV
           echo 'ITEM_CAKE=strawberry' >> $GITHUB_ENV

      - name: Show env
        run: env | grep "$(echo 'item' | tr a-z A-Z)"
        env:
          ITEM_NAME: foo
          ITEM_TITLE: bar
          CODE_NAME: baz

  show-latest-commits:
    name: show latest commit
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: show git log
        run: |
          git log --pretty=format:"[%ad][%an] %h - %s" --date=iso
