name: on push

on:
  push:
    branches:
      - master

jobs:
  merge:
    name: Pushed to master
    runs-on: ubuntu-latest

    steps:
      -
        name: Show github
        run: echo "${OBJ}"
        env:
          OBJ: ${{ toJson(github) }}
      -
         name: show jq path
         run: which jq

      -
         name: set item price
         run: echo 'ITEM_PRICE=300' >> $GITHUB_ENV

      - name: Show env
        run: env | grep ITEM
        env:
          ITEM_NAME: foo
          ITEM_TITLE: bar
          CODE_NAME: baz
